### ISSUE TITLE
issue when I'm trying to train the model

### ISSUE THREAD

**Issue by rikeshprajapati** [924973292/FusionReID#1]
!python train_net.py --config_file /content/FusionReID/configs/Market1501/market_vitb12_res50_layer2.yml

Traceback (most recent call last):
  File "/content/FusionReID/train_net.py", line 3, in <module>
    from modeling import make_model
  File "/content/FusionReID/modeling/__init__.py", line 1, in <module>
    from .make_model import make_model
  File "/content/FusionReID/modeling/make_model.py", line 8, in <module>
    from modeling.backbones.swin import swin_base_patch4_win8
ModuleNotFoundError: No module named 'modeling.backbones.swin'

**Comment by 924973292** [comment]
Thanks for your attention. I've updated the code. Just remove the swin... will be ok.
